<?php

namespace App\Models\Database;

use App\Entities\Database\Decomp\UserToScheduleDecompEntity;

class UserToScheduleDatabase extends BaseDatabase
{
	const TABLE_NAME = "zakphb_user_to_schedule";
	const ENTITY_NAME = UserToScheduleDecompEntity::class;
	public function __construct()
	{
		parent::__construct(self::TABLE_NAME, self::ENTITY_NAME);
	}

	public function save($data): string
	{
		return parent::save($data); // TODO: Change the autogenerated stub
	}

	public function insert(array $data)
	{
		return parent::insert($data); // TODO: Change the autogenerated stub
	}

	public function update($data)
	{
		return parent::update($data); // TODO: Change the autogenerated stub
	}

	public function exists($data)
	{
		return parent::exists($data); // TODO: Change the autogenerated stub
	}

	public function deleteById($data)
	{
		return parent::deleteById($data); // TODO: Change the autogenerated stub
	}

	public function deleteWhere($data)
	{
		return parent::deleteWhere($data); // TODO: Change the autogenerated stub
	}

	public function getWhere($data, int $numberOfResults = 100)
	{
		return parent::getWhere($data, $numberOfResults); // TODO: Change the autogenerated stub
	}

	public function getById($data)
	{
		return parent::getById($data); // TODO: Change the autogenerated stub
	}

	public function getAll()
	{
		return parent::getAll(); // TODO: Change the autogenerated stub
	}
}