<?php
namespace App\Enums\ActionConstructors;

class ELoginConstructor extends EBaseActionConstructor
{
	const CONTROLLER_NAME = "login";
	static function login(string $controllerName = self::CONTROLLER_NAME)
	{
		return parent::login($controllerName); // TODO: Change the autogenerated stub
	}

	static function register(string $controllerName = self::CONTROLLER_NAME)
	{
		return parent::register($controllerName); // TODO: Change the autogenerated stub
	}

	static function logout(string $controllerName = self::CONTROLLER_NAME)
	{
		return parent::logout($controllerName); // TODO: Change the autogenerated stub
	}

	static function show(string $controllerName = self::CONTROLLER_NAME)
	{
		return parent::show($controllerName); // TODO: Change the autogenerated stub
	}

	static function showRegister($controllerName = self::CONTROLLER_NAME)
	{
		return $controllerName . '.' . 'showRegister';// TODO: Change the autogenerated stub
	}

}