<?php

namespace App\Enums\ActionConstructors;

use App\Enums\EControllerNames;

class EProfileConstructor extends EBaseActionConstructor
{
	const CONTROLLER_NAME = "profile";

	static function edit(string $controllerName = self::CONTROLLER_NAME)
	{
		return parent::edit($controllerName); // TODO: Change the autogenerated stub
	}

	static function delete(string $controllerName = self::CONTROLLER_NAME)
	{
		return parent::delete($controllerName); // TODO: Change the autogenerated stub
	}

	static function detail(string $controllerName = self::CONTROLLER_NAME)
	{
		return parent::detail($controllerName); // TODO: Change the autogenerated stub
	}

	static function grid(string $controllerName = self::CONTROLLER_NAME)
	{
		return parent::grid($controllerName); // TODO: Change the autogenerated stub
	}

	static function show(string $controllerName = self::CONTROLLER_NAME)
	{
		return parent::show($controllerName); // TODO: Change the autogenerated stub
	}

	static function join(string $controllerName = self::CONTROLLER_NAME)
	{
		return parent::join($controllerName);
	}

	static function allow(string $controllerName = EControllerNames::PROFILE)
	{
		return parent::allow($controllerName);
	}
}