<?php

namespace App\Controllers;

use App\Entities\Database\Object\BaseObjectEntity;
use App\Enums\ActionConstructors\EPermissionConstructor;
use App\Models\Database\PermissionDatabase;
use App\Models\Facade\PermissionFacade;
use App\Utilities\RedirectUtils;

/**
 *
 */
class PermissionController extends BaseController
{
	public const VIEW_GRID = "src/Views/Permission/grid.latte";
	public const VIEW_EDIT = "src/Views/Permission/edit.latte";
	protected $controllerName = EPermissionConstructor::CONTROLLER_NAME;

	/**
	 * @param $latte
	 */
	public function __construct($latte)
	{
		parent::__construct($latte);
		$this->permissionFacade = new PermissionFacade(new PermissionDatabase());
	}

	/**
	 * @param string $path
	 * @param array $args
	 * @return mixed
	 */
	public function show(string $path = self::VIEW_EDIT, $args = [])
	{
		if ($path === self::VIEW_EDIT)
		{
			$args['selectNames'] = $this->permissionFacade->getControllersForPermissions();
		}
		return parent::show($path, $args); // TODO: Change the autogenerated stub
	}

	/**
	 * @return mixed|void
	 */
	public function actionEdit()
	{
		parent::actionEdit(); // TODO: Change the autogenerated stub
	}

	/**
	 *
	 */
	public function actionDelete()
	{
		$variablesGet = $_GET;
	}

	/**
	 * @param $variables
	 * @return mixed|string
	 */
	public function saveForm($variables)
	{
		return $this->permissionFacade->savePermission($variables);
	}

	/**
	 * @param $variables
	 * @return mixed|void
	 */
	public function loadForm($variables)
	{
		$args['formData'] = $this->permissionFacade->getPermissionById($variables[BaseObjectEntity::BASE_ID]);
		$this->show(self::VIEW_EDIT, $args);
	}

	/**
	 * @param $id
	 * @return mixed|void
	 */
	public function redirectEdit($id)
	{
		RedirectUtils::redirectWithURLBuild(EPermissionConstructor::edit(), [BaseObjectEntity::BASE_ID => $id]);
	}

	/**
	 * @return mixed|void
	 */
	public function actionGrid()
	{
		$gridValues = $this->permissionFacade->getAllPermissions();
		$args["gridvalues"] = $gridValues;
		$this->show(self::VIEW_GRID, $args);
	}

}