<?php

namespace App\Controllers;

use App\Entities\Database\Object\BaseObjectEntity;
use App\Enums\ActionConstructors\EScheduleConstructor;
use App\Models\Database\ScheduleDatabase;
use App\Models\Database\UserToScheduleDatabase;
use App\Models\Facade\ScheduleFacade;
use App\Utilities\RedirectUtils;

class ScheduleController extends BaseController
{
	public const VIEW_GRID = "src/Views/Schedule/grid.latte";
	public const VIEW_EDIT = "src/Views/Schedule/edit.latte";
	protected string $controllerName = EScheduleConstructor::CONTROLLER_NAME;

	/**
	 * @param $latte
	 */
	public function __construct($latte)
	{
		parent::__construct($latte);
		$this->scheduleFacade = new ScheduleFacade(new ScheduleDatabase(), new UserToScheduleDatabase());
	}

	/**
	 * @param string $path
	 * @param array $args
	 * @return mixed
	 */
	public function show(string $path = self::VIEW_EDIT, $args = [])
	{
		if ($path === self::VIEW_EDIT){
			$args['selectHobbyGroups'] = $this->scheduleFacade->hobbygroupFacade->getAllHobbyGroups();
			$args['selectSchoolrooms'] = $this->scheduleFacade->schoolroomFacade->getAllSchoolrooms();
		}
		return parent::show($path, $args); // TODO: Change the autogenerated stub
	}

	/**
	 * @return mixed|void
	 */
	public function actionGrid()
	{
		$gridValues = $this->scheduleFacade->getAllSchedules();
		$args["gridvalues"] = $gridValues;
		$this->show(self::VIEW_GRID, $args);
	}

	/**
	 * @param $variables
	 * @return mixed|string
	 */
	public function saveForm($variables)
	{
		return $this->scheduleFacade->saveSchedule($variables);
	}

	/**
	 * @param $variables
	 * @return mixed|void
	 */
	public function loadForm($variables)
	{
		$args['formData'] = $this->scheduleFacade->getFullSchedule($variables[BaseObjectEntity::BASE_ID]);
		$this->show(self::VIEW_EDIT, $args);
	}

	/**
	 * @param $id
	 * @return mixed|void
	 */
	public function redirectEdit($id)
	{
		RedirectUtils::redirectWithURLBuild(EScheduleConstructor::edit(), [BaseObjectEntity::BASE_ID => $id]);
	}

	/**
	 * @return mixed|void
	 */
	public function actionEdit()
	{
		parent::actionEdit(); // TODO: Change the autogenerated stub
	}
}